#!/usr/bin/env node

/**
 * Module dependencies.
 */

var app = require('./app');
var debug = require('debug')('copytrade-dashboard:server');
var http = require('http');
var {closeGrpc, setConsul,consulkv} = require('./testingGrpc');
/**
 * Get port from environment and store in Express.
 */
var arguments = process.argv.splice(2);
var dport = arguments[0]||9098;
var dconsulip = arguments[1]||consulkv.host;
var dconsulport = arguments[2]||consulkv.port;

var consularg = {
    host: dconsulip.toString(),
    port: +dconsulport
}
setConsul(consularg);
console.log("start config | port is :",dport,"| consul is",consularg);
var port = normalizePort(process.env.PORT || dport);
app.set('port', port);

/**
 * Create HTTP server.
 */

var server = http.createServer(app);

/**
 * Listen on provided port, on all network iiiiiiinterfaces.
 */



server.listen(port);
server.on('error', onError);
server.on('listening', onListening);
/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}



process.on('SIGINT', function() {
  closeGrpc();
  process.exit(0);
});

process.on('exit', function() {
  closeGrpc();
});
